name: tuple_dart
description: A library providing a tuple data structure for Dart
version: 1.1.0
homepage: https://github.com/avdosev
repository: https://github.com/avdosev/tuple_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
